# Copyright (C) 2023 Javier Albiero (jalbiero)
# Distributed under the MIT License (see the accompanying LICENSE file
# or go to http://opensource.org/licenses/MIT).

services:
  bun:
    build:
      context: apps/bun
    image: jalbiero/test-bun
    ports:
      - ${BUN_PORT}:8000
  cpp:
    build:
      context: apps/c++
    image: jalbiero/test-cpp
    ports:
      - ${CPP_PORT}:8000
  charp:
    build:
      context: apps/charp
    image: jalbiero/test-csharp
    ports:
      - ${CSHARP_PORT}:8000
  deno:
    build:
      context: apps/deno
    image: jalbiero/test-deno
    ports:
      - ${DENO_PORT}:8000
  java:
    build:
      context: apps/java
    image: jalbiero/test-java
    ports:
      - ${JAVA_PORT}:8000
  nodejs:
    build:
      context: apps/nodejs
    image: jalbiero/test-nodejs
    ports:
      - ${NODEJS_PORT}:8000
  python:
    build:
      context: apps/python
    image: jalbiero/test-python
    ports:
      - ${PYTHON_PORT}:8000
  rust:
    build:
      context: apps/rust
    image: jalbiero/test-rust
    ports:
      - ${RUST_PORT}:8000
