# Copyright (C) 2023 Javier Albiero (jalbiero)
# Distributed under the MIT License (see the accompanying LICENSE file
# or go to http://opensource.org/licenses/MIT).

services:
  bun:
    image: jalbiero/test-bun
    ports:
      - ${BUN_PORT}:8000
  cpp:
    image: jalbiero/test-cpp
    ports:
      - ${CPP_PORT}:8000
  deno:
    image: jalbiero/test-deno
    ports:
      - ${DENO_PORT}:8000
  java:
    image: jalbiero/test-java
    ports:
      - ${JAVA_PORT}:8000
  nodejs:
    image: jalbiero/test-nodejs
    ports:
      - ${NODEJS_PORT}:8000
  python:
    image: jalbiero/test-python
    ports:
      - ${PYTHON_PORT}:8000
  rust:
    image: jalbiero/test-rust
    ports:
      - ${RUST_PORT}:8000
